# Python Script For getting tweets and storing in JSON

In [13]:
'''
Tweepy neccessary libraries for authentication and fetching of tweets.
'''

from tweepy import API 
from tweepy import Cursor
from tweepy import OAuthHandler

import numpy as np                                                    
import pandas as pd                                                   
import json

Function for Twitter Authentication

In [14]:
def twitter_authentication(consumer_key,consumer_secret,access_token,access_token_secret):
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = API(auth)
    return api

Function for getting client timeline data

In [15]:
def get_client_timeline_tweets(api,twitter_user):
        tweets = []
        for tweet in Cursor(api.user_timeline, id=twitter_user).items():
            tweets.append(tweet)
        return tweets

Function for putting tweets into dataframe

In [16]:
def tweets_to_data_frame(tweets):
        df = pd.DataFrame(data=[tweet.text for tweet in tweets], columns=['Tweets'])

        df['Len'] = np.array([len(tweet.text) for tweet in tweets])
        df['Date Time'] = np.array([str(tweet.created_at) for tweet in tweets])
        df['Likes'] = np.array([tweet.favorite_count for tweet in tweets])
        df['Retweets'] = np.array([tweet.retweet_count for tweet in tweets])

        return df

CONSUMER KEYS AND TOKENS

In [17]:
# consumer_key = 'kNliI2PUQNTSSRsy56PtW59eP'
# consumer_secret = 'y2LHQblAu4fNduL5K3xriqDwI9X8JTJz3aZDbjay1Ft5eOQFpN'
# access_token = '282632401-EeQlM6CVNQ6NrFFuFjCSQz9M7gFSN9TRu8O91zq0'
# access_token_secret = 'qdttjDSIWLxD3XzJ8tn76JSlWSRVIs1NbaAMbmryLaCB1'

Authenticating Consumer Keys

In [18]:
api = twitter_authentication(consumer_key,consumer_secret,access_token,access_token_secret)

Selecting Client.

In [19]:
twitter_user = "midasIIITD "

Getting Clent timeline

In [20]:
tweets=get_client_timeline_tweets(api,twitter_user,)

Converting Tweets into DataFrame

In [21]:
df=tweets_to_data_frame(tweets)

Converting DataFrame into Jsonlines

In [22]:
df.to_json("tweets.json",orient = "records")

In [23]:
df

,Tweets,Len,Date Time,Likes,Retweets
0,Clarification: Our earlier post which indicate...,139,2019-04-10 09:01:29,0,0
1,RT @IIITDelhi: Applications open for MTech (CB...,139,2019-04-10 04:51:26,0,1
2,RT @IIITDelhi: We are delighted to share that ...,140,2019-04-09 16:45:07,0,14
3,RT @Harvard: Professor Jelani Nelson founded A...,136,2019-04-09 05:04:27,0,35
4,RT @emnlp2019: For anyone interested in submit...,140,2019-04-09 05:04:11,0,17
5,RT @multimediaeval: Announcing the 2019 MediaE...,140,2019-04-08 19:38:09,0,15
6,"Many Congratulations to @midasIIITD student, S...",140,2019-04-08 07:08:12,18,2
7,@midasIIITD thanks all students who have appea...,140,2019-04-08 03:27:42,5,0
8,"@himanchalchandr Meanwhile, complete CV/NLP ta...",55,2019-04-07 14:17:29,0,0
9,@sayangdipto123 Submit as per the guideline ag...,50,2019-04-07 14:17:09,0,0
10,We request all students whose interview are sc...,140,2019-04-07 11:43:24,1,1
11,"Other queries: ""none of the Tweeter Apis give ...",139,2019-04-07 06:55:19,5,2
12,"Other queries: ""do we have to make two differe...",140,2019-04-07 06:53:38,4,1
13,"Other queries: ""If using Twitter api, it does ...",140,2019-04-07 05:32:27,6,1
14,Response to some queries asked by students on ...,140,2019-04-07 05:29:40,7,1
15,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,89,2019-04-06 17:11:29,0,2
16,@nupur_baghel @PennDATS Congratulation @nupur_...,140,2019-04-06 16:43:27,18,3
17,We have emailed the task details to all candid...,140,2019-04-05 16:08:37,11,1
18,RT @rfpvjr: Our NAACL paper on polarization in...,139,2019-04-05 04:05:11,0,16
19,RT @kdnuggets: Effective Transfer Learning For...,98,2019-04-05 04:04:43,0,11
20,RT @stanfordnlp: What’s new in @Stanford CS224...,140,2019-04-03 18:31:53,0,59
21,RT @DeepMindAI: Today we're releasing a large-...,140,2019-04-03 17:04:32,0,872
22,RT @ylecun: Congratulations Jitendra Malik !\n...,113,2019-04-03 09:03:40,0,16
23,RT @IIITDelhi: Another chance to take admissio...,140,2019-04-03 07:46:02,0,4
24,Dear @midasIIITD internship candidates who hav...,140,2019-04-02 04:20:13,8,1
25,Looking forward to your paper submission to @I...,140,2019-04-02 02:44:54,5,1
26,RT @ngrams: Reproducibility in multimedia rese...,140,2019-04-02 02:35:44,0,7
27,Online application for https://t.co/DJFDrQsHZP...,140,2019-04-01 06:53:08,7,2
28,RT @ACMMM19: A final reminder of the Reproduci...,140,2019-03-31 10:21:24,0,10
29,RT @isarth23: Thanks for the support and help ...,140,2019-03-29 19:43:24,0,2
...,...,...,...,...,...
314,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,140,2018-08-09 05:59:57,0,265
315,@midasIIITD is looking for motivated IIITD MTe...,140,2018-08-08 11:30:56,2,1
316,@IIITDelhi @ponguru @RatnRajiv The results of ...,96,2018-08-08 05:53:48,3,1
317,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,140,2018-08-08 05:45:58,0,1
318,RT @kdnuggets: Comparison of Top 6 Python NLP ...,103,2018-08-07 07:16:33,0,40
319,Check more details of the 20th IEEE Internatio...,118,2018-08-07 02:05:12,1,1
320,MR2AMC@ISM 2018 will be organized by @RatnRaji...,135,2018-08-07 01:58:49,1,1
321,"Our workshop proposal named, ""MR2AMC: Multimod...",140,2018-08-07 01:50:33,1,1
322,@NUSComputing Congratulations Abdelhak and Pro...,59,2018-08-06 17:48:23,0,0
323,RT @goodfellow_ian: One of the most anticipate...,123,2018-08-06 17:46:59,0,103
324,@the_dhumketu Great to have you in @midasIIITD,46,2018-08-06 06:06:47,0,0
325,Congratulation @soujanyaporia for being appoin...,140,2018-08-03 05:56:33,6,1
326,@IIITDelhi @the_dhumketu Thanks team @midasIII...,72,2018-08-01 11:47:15,5,1
327,RT @IIITDelhi: Congratulations @midasIIITD int...,140,2018-08-01 11:20:07,0,4
328,RT @learning_pt: Profile of the 5 Indian under...,140,2018-08-01 05:06:47,0,4
329,Have a look at the list of accepted papers in ...,140,2018-07-31 12:11:52,1,0
330,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...,139,2018-07-31 02:06:26,0,264
331,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,140,2018-07-30 07:30:51,0,2
332,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",140,2018-07-28 11:07:11,0,57
333,RT @kdnuggets: .@Bloomberg launches free cours...,140,2018-07-28 06:14:09,0,105
334,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,124,2018-07-28 06:13:48,0,7
335,RT @IIITDelhi: We are delighted to announce th...,140,2018-07-28 04:08:21,0,6
336,Get ready for the annual technical fest of @II...,140,2018-07-27 06:46:44,3,2
337,Congratulations Dr. @RatnRajiv and team @midas...,139,2018-07-27 04:07:31,8,2
338,Congratulations MIDAS @midasIIITD intern Prakh...,140,2018-07-25 05:14:35,5,1
339,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm,47,2018-07-24 10:33:23,2,1
340,It feels great to be the part of @IIITDelhi. h...,68,2018-07-24 10:12:34,2,1
341,"Thank you, @toonzratn for designing the logo o...",78,2018-07-24 09:46:26,4,1
342,We are on Facebook too. Like our page to get o...,121,2018-07-23 16:25:05,3,1
343,MIDAS is a group of researchers at IIIT-Delhi ...,140,2018-07-23 12:53:15,7,4